spring:
 cloud:
  gateway:
   routes:
   - id: StudentModule
     uri: http://localhost:8082/
     predicates:
     - Path=/student/**
   - id: SchoolModule
     uri : http://localhost:8081/
     predicates:
     - Path=/school/**
