server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host:localhost
    port:5672
    username:guest
    password:guest
  cloud:
    stream:
      bindings:
        input:
          destination: userRegistrations
          group: userRegistrationQueue

